### ISSUE TITLE
Log files not being created

### ISSUE THREAD

**Issue by AlexanderJLong** [Computer-Vision-in-the-Wild/Elevater_Toolkit_IC#8]
Thankyou for your work and on releasing this benchmark. I am trying to verify zero-shot results and was going to just grep the log files, but they are not being created when I run run.sh. Do you have any pointers on this? Is there a better way to accumulate results over multiple runs?

**Comment by haotian-liu** [comment]
Hi @AlexanderJLong
There was some changes in the upstream `vision-datasets` which was causing the log issue.  It has been fixed in https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC/commit/4ddfdc5a3b9b6eb0536b6d425c40de40859d4717, by fixing the version strictly of `vision-datasets` and `vision-evaluation` packages.  Thanks.
